swagger: '2.0'
info:
  version: '1.0'
  title: "esercitazione11.12"
  description: Esercitazione svolta in classe l'11/12/2018.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: esercitazionesi2.herokuapp.com
basePath: /
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /square:
    x-summary: Primary Function
    get:
      summary: Square Function
      parameters:
        - in: body
          name: body
          description: Input usato per calcolare il quadrato
          required: true
          schema:
            $ref: '#/definitions/String'
      responses:
        200:
          description: Successful Response
          schema:
            type: array
            items:
              $ref: '#/definitions/Result'
          examples:
            application/json:
              - result: 16
        500:
          description: Internal Server Error
definitions:
  String:
    title: String
    type: object
    properties:
      string:
        type: string
        description: Stringa data in input come query
    required:
      - string
  Result:
    title: Result
    type: object
    properties:
      result:
        type: integer
        description: Risultato del calcolo
    required:
      - result